Project setup - Milestone 1
phfdonda/tic-tac-toe pull request #1
Opened 2020-04-03 14:52 UTC by phfdonda

This is the First Milestone for the Tic-Tac-Toe Game Project

2020-04-03 17:59 UTC, shshamim63 requested changes
## Status :trackball: Changes Required :trackball: 
___
Hi @phfdonda :wave: ,
Awesome job :clap: . I can see a bin folder with a main.rb file, a lib folder, the skeleton of a Readme . But have found some issues that are blocking me to approve it right now.
___
### :spades: Mandatory Changes :spades: 
___
1. We want to check the lint based on rubocop specification. For that, you have to change the stickler. Check out this [link](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml) for more info.
2. `main.rb` should be an [executable file](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/):
    - `#!/usr/bin/env ruby` is the top line
    -  puts "Hello world" in the following line
Instead saw those lines on main. So you have to move them.
___
##### Please fix the above-mentioned issues and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-03 17:59 UTC, shshamim63 commented on main
> +p 'Hello World'
These lines should be placed inside bin/main.rb file.

2020-04-03 17:59 UTC, shshamim63 commented on .stickler.yml
> +    config: 'stylelint.config.js'
The config should be  "./rubocop.yml"

2020-04-03 21:19 UTC, phfdonda commented
Hi, @shshamim63! Thank you for the review! Silly mistake, copied the wrong file! There you have it!

2020-04-05 18:11 UTC, pelzolga123 approved these changes

2020-04-05 18:14 UTC, pelzolga123 commented
## Hi Pedro, amazing job :+1:
You did all changes required previously. Just one more thing, you have 2 main files in your project. Please delete one, that is outside bin directory. Then go ahead and merge to development.
 
_Goodluck in your next milestone_ *Happy coding*

2020-04-06 11:25 UTC, merged