User interface - Milestone 2
phfdonda/tic-tac-toe pull request #2
Opened 2020-04-03 14:54 UTC by phfdonda

This is the Second Milestone for the Tic-Tac-Toe Game for Microverse Curriculum

2020-04-03 17:54 UTC, kobiyoyo requested changes
## Hi Team  ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, you are almost there .
### General
-  [ ] Please lets take a step back and look at the guidelines below
![1](https://user-images.githubusercontent.com/23278161/78390429-77b7a380-75dc-11ea-9b48-d3b2cfd82cf2.png)

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-03 21:22 UTC, phfdonda commented
Hi, @kobiyoyo. Thank you for the review.
I don't understand what is wrong with the project. Could you please tell me? Thanks!

2020-04-03 22:14 UTC, phfdonda commented
I think you meant the path problem, I fixed that. Was that it?

2020-04-06 04:12 UTC, majovanilla requested changes
Good work team!! :star: 

You have almost completed this milestone! :muscle: 

Please take a look at the comments below. Remember the instructions posted on the image above by the previous TSE: the objective of this milestone is to have all the game flow _before_ actually coding anything.

You would be surprised of how much :timer_clock: you will save by thinking and :memo:  any project you build... designing the general outline before writing the first line of code!! This is something you should implement on all future and complex projects.

### Please make the necessary adjustments. 
Remember it can be added as comments, but you nee to think of all the flow of your game :space_invader: 

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-06 04:12 UTC, majovanilla commented on bin/main
> +
What happens if the user selects an invalid option? Remember the objective of this milestone:
![Screenshot from 2020-04-05 23-02-32](https://user-images.githubusercontent.com/51926937/78522040-99a65700-7791-11ea-9c3a-10ba1ee1f790.png)

2020-04-06 04:12 UTC, majovanilla commented on bin/main
> +
what happens if no one wins??

2020-04-06 04:12 UTC, majovanilla commented on bin/main
> +
Think about the loop you will have to make to make the turns.

2020-04-06 12:19 UTC, phfdonda commented
Thank you, @majovanilla! That was an excellent review, really well explained! I tried to give a more robust explanation about the game flow in the comments inside the code, I hope that's what is expected.

2020-04-06 16:34 UTC, whiz25 approved these changes
## [APPROVED!] :+1: 
Merge and proceed to the next milestone.

### Martin Afani

2020-04-06 18:15 UTC, merged